Project2/Models/MissionQuestions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Project2.Models
{
    [Table("MissionQuestions")]
    public class MissionQuestions
    {
        [Key]
        public int MissionQuestionID { get; set; }
        public int MissionID { get; set; }
        public int UserID { get; set; }
        public String Question { get; set; }
        public String Answer { get; set; }
    }
}

Project2/Controllers/MissionQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project2.DAL;
using Project2.Models;

namespace Project2.Controllers
{
    public class MissionQuestionsController : Controller
    {
        private Project2Context db = new Project2Context();

        // GET: FAQ
        [Authorize]
        public ActionResult FAQ()
        {
            return View(db.MissionQuestions.ToList());
        }

        // GET: MissionQuestions
        public ActionResult Index()
        {
            return View(db.MissionQuestions.ToList());
        }

        // GET: MissionQuestions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MissionQuestions missionQuestions = db.MissionQuestions.Find(id);
            if (missionQuestions == null)
            {
                return HttpNotFound();
            }
            return View(missionQuestions);
        }

        // GET: MissionQuestions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MissionQuestions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MissionQuestionID,MissionID,UserID,Question,Answer")] MissionQuestions missionQuestions)
        {
            if (ModelState.IsValid)
            {
                db.MissionQuestions.Add(missionQuestions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(missionQuestions);
        }

        // GET: MissionQuestions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MissionQuestions missionQuestions = db.MissionQuestions.Find(id);
            if (missionQuestions == null)
            {
                return HttpNotFound();
            }
            return View(missionQuestions);
        }

        // POST: MissionQuestions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MissionQuestionID,MissionID,UserID,Question,Answer")] MissionQuestions missionQuestions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(missionQuestions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(missionQuestions);
        }

        // GET: MissionQuestions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MissionQuestions missionQuestions = db.MissionQuestions.Find(id);
            if (missionQuestions == null)
            {
                return HttpNotFound();
            }
            return View(missionQuestions);
        }

        // POST: MissionQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MissionQuestions missionQuestions = db.MissionQuestions.Find(id);
            db.MissionQuestions.Remove(missionQuestions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project2/Controllers/MissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project2.DAL;
using Project2.Models;
using Microsoft.AspNet.Identity;

namespace Project2.Controllers
{
    [RequireHttps]
    public class MissionsController : Controller
    {
        private Project2Context db = new Project2Context();

        // GET: Missions
        public ActionResult Index()
        {
            return View(db.Missions.ToList());
        }

        //[HttpPost]
        //public ActionResult MissionInfo(FormCollection form)
        //{
        //    //Variable for mission ID
        //    int MissionID;
        //    //Determines if mission ID is a valid number
        //    bool validMissionID = Int32.TryParse(form["MissionID"], out MissionID);

        //    //Set ViewBag data if the MissionID is a valid number
        //    if (validMissionID && (MissionID == 1 || MissionID == 2 || MissionID == 3))
        //    {
        //        //Brazil Ribeirao Preto Mission
        //        if (MissionID == 1)
        //        {
        //            ViewBag.MissionName = "Brazil Ribeirao Preto";
        //            ViewBag.MissionPresident = "Peter Siegfried Scholz";
        //            ViewBag.MissionAddress = "Rua Sao Sebastiao 1003, Centro, 14015-040 Ribeirao Preto, SP, Brazil";
        //            ViewBag.Language = "Portuguese";
        //            ViewBag.Climate = "Tropical Wet and Dry";
        //            ViewBag.DominateReligion = "Roman Catholic";
        //            ViewBag.FlagImgFileName = "Brazil_Flag.png";
        //        }
        //        //Raleigh North Carolina Mission
        //        else if (MissionID == 2)
        //        {
        //            ViewBag.MissionName = "Raleigh North Carolina";
        //            ViewBag.MissionPresident = "Dennis Roland James";
        //            ViewBag.MissionAddress = "5060 Six Forks Rd, Raleigh, NC 27609";
        //            ViewBag.Language = "English";
        //            ViewBag.Climate = "Humid Subtropical";
        //            ViewBag.DominateReligion = "Protestant Christian";
        //            ViewBag.FlagImgFileName = "USA_Flag.png";
        //        }
        //        //Japan Fukuoka Mission
        //        else if (MissionID == 3)
        //        {
        //            ViewBag.MissionName = "Japan Fukuoka";
        //            ViewBag.MissionPresident = "Bradley C Egan";
        //            ViewBag.MissionAddress = "9-16 Hirao-josuimachi, Chuo-ku, Fukuoka-shi, Fukuoka, 810-0029";
        //            ViewBag.Language = "Japanese";
        //            ViewBag.Climate = "Humid Subtropical";
        //            ViewBag.DominateReligion = "Shinto and Buddhism";
        //            ViewBag.FlagImgFileName = "Japan_Flag.png";
        //        }
        //        //Return view with ViewBag data
        //        return View("MissionInfo");
        //    }
        //    else
        //    {
        //        //Return string stating there was an error
        //        return Content("Error finding data for mission ID " + form["MissionID"]);
        //    }

        //}

        public ActionResult Missions()
        {
            ViewBag.Missions = db.Missions.ToList();

            return View();
        }

        

       [HttpPost]
        [Authorize]
        public ActionResult SelectMission(Missions model)
        {
            var id = model.MissionID;

            IEnumerable<Missions> missionData = db.Database.SqlQuery<Missions>(
                "SELECT * FROM Missions WHERE MissionID = " + model.MissionID).ToList();

            ViewBag.MissionData = missionData;

            IEnumerable<MissionQuestions> missionQuestions = db.Database.SqlQuery<MissionQuestions>(
                "SELECT * FROM MissionQuestions WHERE MissionID = " + model.MissionID).ToList();

            ViewBag.MissionQuestions = missionQuestions;

            ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserEmail = User.Identity.GetUserName();

            return View();
        }

        // GET: Missions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Missions missions = db.Missions.Find(id);
            if (missions == null)
            {
                return HttpNotFound();
            }
            return View(missions);
        }

        // GET: Missions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Missions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MissionID,MissionName,MissionPresident,MissionAddress,MissionLanguage,MissionClimate")] Missions missions)
        {
            if (ModelState.IsValid)
            {
                db.Missions.Add(missions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(missions);
        }

        // GET: Missions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Missions missions = db.Missions.Find(id);
            if (missions == null)
            {
                return HttpNotFound();
            }
            return View(missions);
        }

        // POST: Missions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MissionID,MissionName,MissionPresident,MissionAddress,MissionLanguage,MissionClimate")] Missions missions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(missions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(missions);
        }

        // GET: Missions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Missions missions = db.Missions.Find(id);
            if (missions == null)
            {
                return HttpNotFound();
            }
            return View(missions);
        }

        // POST: Missions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Missions missions = db.Missions.Find(id);
            db.Missions.Remove(missions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project2/Views/MissionQuestions/Create.cshtml
@model Project2.Models.MissionQuestions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MissionQuestions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MissionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project2/Views/MissionQuestions/Delete.cshtml
@model Project2.Models.MissionQuestions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MissionQuestions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MissionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MissionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project2/Views/MissionQuestions/Details.cshtml
@model Project2.Models.MissionQuestions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MissionQuestions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MissionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MissionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MissionQuestionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project2/Views/MissionQuestions/Edit.cshtml
@model Project2.Models.MissionQuestions

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MissionQuestions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MissionQuestionID)

        <div class="form-group">
            @Html.LabelFor(model => model.MissionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project2/Views/MissionQuestions/Index.cshtml
@model IEnumerable<Project2.Models.MissionQuestions>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MissionID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Question)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MissionID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Question)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Answer)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MissionQuestionID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MissionQuestionID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MissionQuestionID })
        </td>
    </tr>
}

</table>*@

<h2>Mission</h2>
<div class="container">
    <div class="row">
        <!--Drop down menu which displays the different missions you can select from-->
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                Select a Mission
                <span class="caret"></span>
            </button>
            <!--When the user selects a mission from the drop down menu the parameters with the associated mission are passed to the next view-->
            <ul class="dropdown-menu">
                @foreach (var item in Model)
                {
                    // Needs to be changed to redirect to the Mission info view
                    <li> @Html.ActionLink(item.MissionName, "Index", "Missions", new { id = item.MissionID }, null)</li>
                }
            </ul>
        </div>

        @*@using (Html.BeginForm("MissionInfo", "Mission", FormMethod.Post))
            {
                //create dropdown menu for possible missions to select
                @Html.DropDownListFor(m => m.MissionID, new List<SelectListItem>
                                   { new SelectListItem{ Text="Brazil - Ribeirao Preto", Value = "1" },
                                    new SelectListItem{ Text="USA - North Carolina - Raleigh", Value = "2" },
                                    new SelectListItem{ Text="Japan - Fukuoka", Value = "3" } },
                             "Select a mission...",
                             new { required = "required" })
                <br /><br />
                //create submit button; dropdown menu selection is required
                <button type="submit" class="btn btn-primary pull-left">
                    Go <span class="glyphicon glyphicon-send"></span>
                </button>
            }*@
    </div>
</div>